# docker-compose.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: mlx-app
    restart: unless-stopped  # <-- Added restart policy
    ports:
      - "${PORT:-8501}:8501"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./app/data:/app/data  # <-- Add this line to mount the data folder

  db:
    image: postgres:16
    container_name: mlx-db
    restart: always  # Keep as is
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
