name: Deploy to Hetzner VPS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/mlx-digit-app
            git pull
            docker-compose up -d --build
